[package]
name = "shapes"
version = "0.1.0"
edition = "2021"

[lib]
name = "shapes"
crate-type = ["cdylib", "lib"]

[[example]]
name = "demo"
path = "examples/demo.rs"

[dependencies]
lazy_static = "1.4"
