[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.80"

[lib]
crate-type =["cdylib"]
path = "mandelbrot.rs"

[[bin]]
name = "mandelbrot"
path = "mandelbrot.rs"
