[package]
name = "create_svg"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.80"

[lib]
crate-type =["cdylib"]
path = "create_svg.rs"

[[bin]]
name = "create_svg"
path = "create_svg.rs"
